name: Test Vite

on: push

jobs:
  test:
    name: Run Vite tests
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v6.0.2

      - name: Install NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Print test result
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ Tests passed"
          else
            echo "❌ Tests failed"
          fi